version: 2.1

orbs:
  android: circleci/android@3.0.2

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/repo

jobs:
  build-test:
    circleci_ip_ranges: true
    executor: android-executor
    docker:
      - image: cimg/openjdk:17.0.13
    resource_class: xlarge
    steps:
      # PRE SETUP
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install --skip-smudge
      - checkout
      - run: git lfs fetch --all
      - run:
          name: Set Secrets File
          command: echo "$SECRETS_FILE" | base64 --decode > secrets.properties
      - run:
          name: Check JDK exists
          command: javac -version
      - run:
          name: Download Platform Tools
          command: |
            cd ..
            mkdir android-sdk
            cd android-sdk
            wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
            unzip platform-tools-latest-linux.zip
      - run:
          name: Download Commandline Tools
          command: |
            cd ..
            cd android-sdk
            mkdir cmdline-tools
            cd cmdline-tools
            wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            unzip commandlinetools-linux-11076708_latest.zip
            mv cmdline-tools latest
      - run:
          name: Set up Android Home
          command: |
            echo '
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
            export PATH=$PATH:$HOME/android-sdk/platform-tools' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Android Home
          command: echo $ANDROID_HOME
      - run:
          name: Accept SDK licenses
          command: |
            yes | sdkmanager --licenses || exit 0
            yes | sdkmanager --update || exit 0

      # SETUP STEP
      - run:
          name: Check Java Version
          command: java -version

      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      # PRE TEST
      - run:
          name: KLint Format
          command: ./gradlew ktlintFormat

      # TEST STEP
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run KLint Check
          command: ./gradlew ktlintCheck
      - run:
          name: Run Code Coverage
          command: ./gradlew koverXmlReportDebug
      #      - run:
      #          name: Run Screenshot Tests
      #          command: ./gradlew verifyPaparazziDebug
      - store_test_results:
          path: core-methods/build/reports/kover/reportDebug.xml

      # DOCUMENTATION STEP
      - run:
          name: Update Dokka Documentation
          command: ./gradlew :core-methods:dokkaHtml

      - persist_to_workspace:
          root: core-methods/build/dokka
          paths: html

      # BUILD STEP
      - run:
          name: Build the app
          command: ./gradlew assemble --stacktrace
      - run:
          name: Archive APK
          command: |
            mkdir -p ~/circleci-artifacts
            cp example/build/outputs/apk/debug/example-debug.apk ~/circleci-artifacts/
      - run:
          name: Archive .AAR
          command: |
            mkdir -p ~/circleci-artifacts
            cp core-methods/build/outputs/aar/core-methods-debug.aar ~/circleci-artifacts/
      - store_artifacts:
          path: ~/circleci-artifacts
          destination: apk


  docs-deploy:
    docker:
      - image: cimg/node:16.17
    steps:
      # PRE SETUP
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install --skip-smudge
      - checkout
      - run: git lfs fetch --all
      - attach_workspace:
          at: core-methods/build/dokka
      - run:
          name: Disable Jekyll for GitHub Pages
          command: touch core-methods/build/dokka/html/.nojekyll
      - run:
          name: Install gh-pages tool
          command: npm install gh-pages@3.2.3 --silent
      - add_ssh_keys:
        fingerprints:
          - "SHA256:CHbCMOR2Mcw/RHacZ+LuEOqsvk0Vis+R3lzMcdpy9y0"
      - run:
          name: Configure Git for deployment
          command: |
            git config --global user.email "ci-build@example.com"
            git config --global user.name "CI Build"
      - run:
          name: Deploy documentation to GitHub Pages
          command: npx gh-pages --dotfiles --message "[skip ci] Updates" --dist core-methods/build/dokka/html

workflows:
  version: 3
  build:
    jobs:
      - build-test
      - docs-deploy:
          requires:
            - build-test
#          filters:
#            branches:
#              only: main
