version: 2.1

orbs:
  android: circleci/android@3.0.2

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/repo

jobs:
  build:
    executor: android-executor
    docker:
      - image: cimg/openjdk:17.0.13
    steps:
      # PRE SETUP
      - run:
          name: Install Git LFS
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install
      - run:
          name: Fetch lfs files
          command: |
            git lfs fetch --all
      - checkout
      - run:
          name: Check JDK exists
          command: javac -version
      - run:
          name: Download Platform Tools
          command: |
            cd ..
            mkdir android-sdk
            cd android-sdk
            wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip
            unzip platform-tools-latest-linux.zip
      - run:
          name: Download Commandline Tools
          command: |
            cd ..
            cd android-sdk
            mkdir cmdline-tools
            cd cmdline-tools
            wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
            unzip commandlinetools-linux-11076708_latest.zip
            mv cmdline-tools latest
      - run:
          name: Set up Android Home
          command: |
            echo '
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin
            export PATH=$PATH:$HOME/android-sdk/platform-tools' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Android Home
          command: echo $ANDROID_HOME
      - run:
          name: Accept SDK licenses
          command: |
            yes | sdkmanager --licenses || exit 0
            yes | sdkmanager --update || exit 0

      # SETUP STEP
      - run:
          name: Check Java Version
          command: java -version

      - run:
          name: Install Dependencies
          command: ./gradlew dependencies

      # PRE TEST
      - run:
          name: KLint Format
          command: ./gradlew ktlintFormat

      # TEST STEP
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run KLint Check
          command: ./gradlew ktlintCheck
      - run:
          name: Run Code Coverage
          command: ./gradlew koverXmlReportDebug
      - run:
          name: Run Screenshot Tests
          command: ./gradlew verifyPaparazziDebug
      - store_test_results:
          path: core-methods/build/reports/kover/reportDebug.xml

      # BUILD STEP
      - run:
          name: Build the app
          command: ./gradlew assemble --stacktrace
      - run:
          name: Archive APK
          command: |
            mkdir -p ~/circleci-artifacts
            cp example/build/outputs/apk/debug/example-debug.apk ~/circleci-artifacts/
      - run:
          name: Archive .AAR
          command: |
            mkdir -p ~/circleci-artifacts
            cp core-methods/build/outputs/aar/core-methods-debug.aar ~/circleci-artifacts/
      - store_artifacts:
          path: ~/circleci-artifacts
          destination: apk

workflows:
  version: 2
  build:
    jobs:
      - build
