version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    working_directory: ~/repo

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd core-methods
            ../gradlew dependencies

      - run:
          name: Build the app
          command: |
            cd core-methods
            ../gradlew build

      - run:
          name: Run Detekt
          command: |
            cd core-methods
            ../gradlew detekt

      - run:
          name: Run KLint
          command: |
            cd core-methods
            ../gradlew ktlintCheck

      - run:
          name: Run unit tests
          command: |
            cd core-methods
            ../gradlew test

workflows:
  version: 2
  build:
    jobs:
      - build
