package com.mercadopago.sdk.android.checkout.domain.model

/**
 * Internal model for the CVV entry screen.
 *
 * Derived from `security_code.screen` in the `/initialization` response via
 * [SecurityCodeScreenOutput]. Present only when the saved card requires CVV input
 * (`security_code.screen` ≠ null and `has_preapproval_scope` = false).
 *
 * @property headerTitle Screen title — translated by the BFF.
 * @property field Configuration for the CVV input field.
 * @property continueButtonLabel Label for the continue button — translated by the BFF.
 * @property expectedLength Expected CVV digit count from `SecurityCodeOutput.length` (3 for Visa/Master, 4 for Amex).
 */
internal data class CVVScreenData(
    val headerTitle: String,
    val field: CVVFieldConfig,
    val continueButtonLabel: String,
    val expectedLength: Int,
)

/**
 * Configuration for the CVV input field inside the CVV screen.
 *
 * @property label Field label — e.g. "Código de seguridad".
 * @property placeholder Placeholder text — generated by the BFF based on CVV length (e.g. "Ej.: 123").
 * @property helper Helper text — e.g. "Está en el reverso de tu tarjeta."
 */
internal data class CVVFieldConfig(
    val label: String,
    val placeholder: String,
    val helper: String,
)
