package com.mercadopago.sdk.android.threeds.adapter

import android.app.Activity
import com.mercadopago.sdk.android.coremethods.domain.provider.ThreeDSProvider
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSAuthenticationModel
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSChallengeResult
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSRequestParams
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSWarning
import com.mercadopago.sdk.android.threeds.adapter.mappers.ThreeDSAuthenticationModelMapper
import com.mercadopago.sdk.android.threeds.adapter.mappers.ThreeDSChallengeResultMapper
import com.mercadopago.sdk.android.threeds.adapter.mappers.ThreeDSRequestParamsMapper
import com.mercadopago.sdk.android.threeds.adapter.mappers.ThreeDSWarningMapper
import com.mercadopago.sdk.android.threeds.interactor.MPThreeDS

/**
 * Adapter that implements the ThreeDSProvider interface from core-methods module.
 * This adapter bridges the gap between the MPThreeDS implementation in the threeds module
 * and the ThreeDSProvider interface expected by core-methods.
 *
 * The adapter pattern allows the two modules to remain decoupled while still being able
 * to work together. It translates calls and data models between the two modules using
 * the mapper classes.
 *
 * Example usage:
 * ```kotlin
 * val threeDS = MPThreeDS.getInstance(context)
 * val adapter = MPThreeDSProviderAdapter(threeDS)
 *
 * val coreMethods = MercadoPagoSDK.getInstance().coreMethods
 * coreMethods.setThreeDSProvider(adapter)
 * ```
 *
 * @param mpThreeDS The MPThreeDS instance to delegate calls to
 */
class MPThreeDSProviderAdapter(
    private val mpThreeDS: MPThreeDS,
) : ThreeDSProvider {

    /**
     * Creates a 3DS transaction for the specified payment method.
     * Delegates to MPThreeDS.createTransaction().
     *
     * @param paymentMethodId The payment method ID to create the transaction for
     */
    override fun createTransaction(paymentMethodId: String) {
        mpThreeDS.createTransaction(paymentMethodId)
    }

    /**
     * Retrieves the authentication request parameters for the current transaction.
     * Delegates to MPThreeDS.getAuthenticationRequestParameters() and converts the result
     * from MPThreeDSRequestParams to ThreeDSRequestParams.
     *
     * @return The authentication request parameters, or null if no transaction is active
     */
    override fun getAuthenticationRequestParameters(): ThreeDSRequestParams? {
        val mpParams = mpThreeDS.getAuthenticationRequestParameters()
        return mpParams?.let { ThreeDSRequestParamsMapper.toThreeDSRequestParams(it) }
    }

    /**
     * Performs the 3DS challenge flow with the provided authentication response.
     * Delegates to MPThreeDS.doChallenge() and converts the parameters and result
     * between the two module's domain models.
     *
     * @param activity The activity context for displaying the challenge UI
     * @param authentication The authentication response received from the backend
     * @param timeout The challenge timeout in minutes
     * @return The result of the challenge flow
     */
    override suspend fun doChallenge(
        activity: Activity,
        authentication: ThreeDSAuthenticationModel,
        timeout: Int,
    ): ThreeDSChallengeResult {
        val mpAuthentication = ThreeDSAuthenticationModelMapper.toMPThreeDSAuthenticationModel(authentication)
        val mpResult = mpThreeDS.doChallenge(
            activity = activity,
            authentication = mpAuthentication,
            timeout = timeout,
        )
        return ThreeDSChallengeResultMapper.toThreeDSChallengeResult(mpResult)
    }

    /**
     * Closes the current 3DS transaction and releases associated resources.
     * Delegates to MPThreeDS.close().
     */
    override fun close() {
        mpThreeDS.close()
    }

    /**
     * Retrieves warnings generated by the 3DS SDK during initialization or operation.
     * Delegates to MPThreeDS.getWarnings() and converts the result from
     * List<MPThreeDSWarning> to List<ThreeDSWarning>.
     *
     * @return A list of warnings, or an empty list if no warnings were generated
     */
    override fun getWarnings(): List<ThreeDSWarning> {
        val mpWarnings = mpThreeDS.getWarnings()
        return ThreeDSWarningMapper.toThreeDSWarningList(mpWarnings)
    }
}
