package com.mercadopago.sdk.android.coremethods.domain.provider

import android.app.Activity
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSAuthenticationModel
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSChallengeResult
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSRequestParams
import com.mercadopago.sdk.android.coremethods.domain.provider.models.ThreeDSWarning

/**
 * Interface defining the contract for 3DS (3-D Secure) operations.
 * This interface allows CoreMethods to interact with 3DS functionality
 * without directly depending on the threeds module.
 *
 * Implementations of this interface should handle:
 * - Transaction creation
 * - Authentication parameter generation
 * - Challenge flow execution
 * - SDK warnings retrieval
 * - Resource cleanup
 *
 * @see ThreeDSRequestParams
 * @see ThreeDSAuthenticationModel
 * @see ThreeDSChallengeResult
 * @see ThreeDSWarning
 */
interface ThreeDSProvider {
    /**
     * Creates a 3DS transaction for the specified payment method.
     *
     * @param paymentMethodId The payment method ID to create the transaction for (e.g., "visa", "mastercard")
     */
    fun createTransaction(paymentMethodId: String)

    /**
     * Retrieves the authentication request parameters for the current transaction.
     * These parameters should be sent to the backend for 3DS authentication.
     *
     * @return The authentication request parameters, or null if no transaction is active
     */
    fun getAuthenticationRequestParameters(): ThreeDSRequestParams?

    /**
     * Performs the 3DS challenge flow with the provided authentication response.
     * This is a suspending function that will display the challenge UI and wait for completion.
     *
     * @param activity The activity context for displaying the challenge UI
     * @param authentication The authentication response received from the backend
     * @param timeout The challenge timeout in minutes (default: 10)
     * @return The result of the challenge flow
     */
    suspend fun doChallenge(
        activity: Activity,
        authentication: ThreeDSAuthenticationModel,
        timeout: Int,
    ): ThreeDSChallengeResult

    /**
     * Closes the current 3DS transaction and releases associated resources.
     * This should be called when the 3DS flow is complete or cancelled.
     */
    fun close()

    /**
     * Retrieves warnings generated by the 3DS SDK during initialization or operation.
     *
     * @return A list of warnings, or an empty list if no warnings were generated
     */
    fun getWarnings(): List<ThreeDSWarning>
}
